In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import Lasso, Ridge
import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_table("/content/CarPrice_Assignment.csv",sep=",")

In [7]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [8]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [12]:
df.select_dtypes(object).columns

Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber',
       'fuelsystem'],
      dtype='object')

In [13]:
catcol=df.select_dtypes(object).columns

In [15]:
oe=OrdinalEncoder()
df[catcol]=oe.fit_transform(df[catcol])
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1.0,1.0,0.0,1.0,2.0,2.0,0.0,94.5,...,152,5.0,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4.0,1.0,0.0,0.0,3.0,1.0,0.0,99.8,...,109,5.0,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5.0,1.0,0.0,0.0,3.0,0.0,0.0,99.4,...,136,5.0,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139.0,1.0,0.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,138.0,1.0,1.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,140.0,1.0,0.0,0.0,3.0,2.0,0.0,109.1,...,173,5.0,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,142.0,0.0,1.0,0.0,3.0,2.0,0.0,109.1,...,145,3.0,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,143.0,1.0,1.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,9.5,114,5400,19,25,22625.0

In [20]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [22]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.3,random_state=1)

In [25]:
linreg = LinearRegression()
linreg.fit(xtrain,ytrain)
y_pred=linreg.predict(xtest)
r2=r2_score(ytest,y_pred)
print(f"r2: {r2}")

r2: 0.8301745621420107

In [26]:
train=linreg.score(xtrain,ytrain)
test=linreg.score(xtest,ytest)
print(f"train score: {train}")
print(f"test score: {test}")

train score: 0.9191177361812822
test score: 0.8301745621420107

In [32]:
X = df[['CarName', 'enginesize', 'fueltype', 'horsepower']]
y = df['price']
catcol = ['CarName', 'fueltype']
oe = OrdinalEncoder()
X[catcol] = oe.fit_transform(X[catcol])
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)
linreg = LinearRegression()
linreg.fit(xtrain, ytrain)
y_pred = linreg.predict(xtest)
r2 = r2_score(ytest, y_pred)
print(f"r2: {r2}")

r2: 0.8564522206148582

In [34]:
while True:
    car_name = input("\nEnter Car Name: ")
    enginesize = int(input("Enter Engine Size: "))
    fueltype = input("Enter Fuel Type (gas/diesel): ")
    horsepower = int(input("Enter Horsepower: "))
    new_car = pd.DataFrame([{
        'CarName': car_name,
        'enginesize': enginesize,
        'fueltype': fueltype,
        'horsepower': horsepower
    }])
    new_car[catcol] = oe.transform(new_car[catcol])
    price = linreg.predict(new_car)
    print("\n==============================")
    print(f"Predicted Car Price: ₹{price[0]:,.2f}")
    print("==============================")
    again = input("\nPredict another car? (yes/no): ")
    if again.lower() != "yes":
        break

Enter Car Name: bmw x3
Enter Engine Size: 164
Enter Fuel Type (gas/diesel): gas
Enter Horsepower: 121

ValueError: Found unknown categories ['bmw x3'] in column 0 during transform